version: "3.8"

services:
  backend:
    build: ./BE
    container_name: webrtc_backend
    env_file: ./BE/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: ./FE
    container_name: webrtc_frontend
    env_file: ./FE/.env
    ports:
      - "3000:3000"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: webrtc_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data:
